<a href="https://colab.research.google.com/github/Abs-CV/Next-Word-Prediction-with-NLP-and-Deep-Learning/blob/main/Next_Word_Prediction_with_NLP_and_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding
from keras.preprocessing import sequence

In [7]:
from keras.preprocessing.text import Tokenizer
import numpy as np
from keras.utils import to_categorical

In [8]:
data = """ Jack and Jill went up the hill\n
		To fetch a pail of water\n
		Jack fell down and broke his crown\n
		And Jill came tumbling after\n """

In [15]:
# integer encode text
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encoded = tokenizer.texts_to_sequences([data])[0]

In [ ]:
encoded

In [16]:
# determine the vocabulary size
vocab_size = len(tokenizer.word_index) + 1
print('Vocabulary Size: %d' % vocab_size)

Vocabulary Size: 22


In [44]:
# create word -> word sequences
sequences = list()
for i in range(1, len(encoded)):
	sequence = encoded[i-1:i+1]
	sequences.append(sequence)
print('Total Sequences: %d' % len(sequences))

Total Sequences: 24


In [45]:
sequences

[[2, 1],
 [1, 3],
 [3, 4],
 [4, 5],
 [5, 6],
 [6, 7],
 [7, 8],
 [8, 9],
 [9, 10],
 [10, 11],
 [11, 12],
 [12, 13],
 [13, 2],
 [2, 14],
 [14, 15],
 [15, 1],
 [1, 16],
 [16, 17],
 [17, 18],
 [18, 1],
 [1, 3],
 [3, 19],
 [19, 20],
 [20, 21]]

In [46]:
# split into X and y elements
sequences = np.array(sequences)
X, y = sequences[:,0],sequences[:,1]

In [47]:
# one hot encode outputs
y = to_categorical(y, num_classes=vocab_size)
y.shape

(24, 22)

In [48]:
# define model
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 1, 10)             220       
                                                                 
 lstm_1 (LSTM)               (None, 50)                12200     
                                                                 
 dense_1 (Dense)             (None, 22)                1122      
                                                                 
Total params: 13,542
Trainable params: 13,542
Non-trainable params: 0
_________________________________________________________________
None


In [63]:
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit network
model.fit(X, y, epochs=1000, verbose=2)

Epoch 1/1000
1/1 - 2s - loss: 0.2454 - accuracy: 0.8750 - 2s/epoch - 2s/step
Epoch 2/1000
1/1 - 0s - loss: 0.2443 - accuracy: 0.8750 - 13ms/epoch - 13ms/step
Epoch 3/1000
1/1 - 0s - loss: 0.2432 - accuracy: 0.8750 - 13ms/epoch - 13ms/step
Epoch 4/1000
1/1 - 0s - loss: 0.2421 - accuracy: 0.8750 - 13ms/epoch - 13ms/step
Epoch 5/1000
1/1 - 0s - loss: 0.2411 - accuracy: 0.8750 - 9ms/epoch - 9ms/step
Epoch 6/1000
1/1 - 0s - loss: 0.2400 - accuracy: 0.8750 - 8ms/epoch - 8ms/step
Epoch 7/1000
1/1 - 0s - loss: 0.2390 - accuracy: 0.8750 - 8ms/epoch - 8ms/step
Epoch 8/1000
1/1 - 0s - loss: 0.2381 - accuracy: 0.8750 - 7ms/epoch - 7ms/step
Epoch 9/1000
1/1 - 0s - loss: 0.2371 - accuracy: 0.8750 - 9ms/epoch - 9ms/step
Epoch 10/1000
1/1 - 0s - loss: 0.2362 - accuracy: 0.8750 - 8ms/epoch - 8ms/step
Epoch 11/1000
1/1 - 0s - loss: 0.2353 - accuracy: 0.8750 - 9ms/epoch - 9ms/step
Epoch 12/1000
1/1 - 0s - loss: 0.2344 - accuracy: 0.8750 - 8ms/epoch - 8ms/step
Epoch 13/1000
1/1 - 0s - loss: 0.2335 - accur

In [70]:
# evaluate
in_text = 'hill'
print(in_text)
encoded = tokenizer.texts_to_sequences([in_text])[0]
encoded = np.array(encoded)
# yhat = model.predict_classes(encoded, verbose=0)
predict_x=model.predict(encoded) 
yhat=np.argmax(predict_x,axis=1)
for word, index in tokenizer.word_index.items():
	if index == yhat:
		print(word)

hill
[7]
1/1 [==============================] - 0s 79ms/step
to


In [69]:
encoded

array([7])

In [79]:
predict_x

array([[5.08992116e-07, 6.60946640e-08, 4.95779705e-06, 4.86893896e-06,
        7.03791466e-06, 1.32603577e-06, 7.85045449e-06, 1.42542973e-07,
        9.99876976e-01, 1.34037646e-06, 2.87082275e-06, 2.12961004e-05,
        7.80818610e-08, 3.30790208e-05, 6.05447849e-06, 4.42444252e-06,
        3.28775627e-06, 1.15487455e-05, 7.05818621e-08, 1.22513256e-05,
        4.11982342e-08, 2.50342662e-08]], dtype=float32)

In [82]:
np.argmax(predict_x[0])

8

In [85]:
predict_x[0]

array([5.08992116e-07, 6.60946640e-08, 4.95779705e-06, 4.86893896e-06,
       7.03791466e-06, 1.32603577e-06, 7.85045449e-06, 1.42542973e-07,
       9.99876976e-01, 1.34037646e-06, 2.87082275e-06, 2.12961004e-05,
       7.80818610e-08, 3.30790208e-05, 6.05447849e-06, 4.42444252e-06,
       3.28775627e-06, 1.15487455e-05, 7.05818621e-08, 1.22513256e-05,
       4.11982342e-08, 2.50342662e-08], dtype=float32)